# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keel < Formula
  desc ""
  homepage "https://github.com/teamkeel/cli"
  version "0.313.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/teamkeel/cli/releases/download/v0.313.7/cli_0.313.7_Darwin_arm64.tar.gz"
      sha256 "b21b56c429b7a4884e008aeddaa50c1ef087c9f3a1bf6c180e435cbe8a485bd0"

      def install
        bin.install "cli" => "keel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/teamkeel/cli/releases/download/v0.313.7/cli_0.313.7_Darwin_x86_64.tar.gz"
      sha256 "16e5a8b6a2f08505cd9217627e2d2de6427b720c790fde13a93cb7a3bb455540"

      def install
        bin.install "cli" => "keel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/teamkeel/cli/releases/download/v0.313.7/cli_0.313.7_Linux_arm64.tar.gz"
      sha256 "577930c324ff6abefd1a21ceb9933e766332f9a7c23bd79a2ca148a2184cf75d"

      def install
        bin.install "cli" => "keel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/teamkeel/cli/releases/download/v0.313.7/cli_0.313.7_Linux_x86_64.tar.gz"
      sha256 "bcb047855c33afe729162f797c78b86736433d9b791ce8de30e5c44144437f03"

      def install
        bin.install "cli" => "keel"
      end
    end
  end
end
