# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keel < Formula
  desc ""
  homepage "https://github.com/teamkeel/cli"
  version "0.374.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/teamkeel/cli/releases/download/v0.374.0/cli_0.374.0_Darwin_x86_64.tar.gz"
      sha256 "b8b1037694269768fda8dab7dafbb5fb6aaed33a8e1e7e3f9d8fa9a7b768065a"

      def install
        bin.install "cli" => "keel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/teamkeel/cli/releases/download/v0.374.0/cli_0.374.0_Darwin_arm64.tar.gz"
      sha256 "1a5fef57bfe3973f9d03426f5c9dc4139c674b6e9779d82acfec4c1ab383b11c"

      def install
        bin.install "cli" => "keel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/teamkeel/cli/releases/download/v0.374.0/cli_0.374.0_Linux_arm64.tar.gz"
      sha256 "7f5cad5546edb7198e93fe529f6f470166d5a5aa63fa9d02aa04e90f2d13a750"

      def install
        bin.install "cli" => "keel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/teamkeel/cli/releases/download/v0.374.0/cli_0.374.0_Linux_x86_64.tar.gz"
      sha256 "7e8e31d7c4ac80334ed1d3ac7d299b7607fd4533bdaec9cf2e7caea987da48a3"

      def install
        bin.install "cli" => "keel"
      end
    end
  end
end
